# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'API V1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for API V1

end

target 'Core' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Core

end

target 'DBCoreData' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DBCoreData

end

target 'DBRealm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DBRealm
  pod 'RealmSwift', '~>10'

end

target 'FileManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FileManager

end

target 'Logger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Logger

end

target 'PPOcards' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PPOcards
  pod 'RealmSwift', '~>10'

  target 'IntegrationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UnitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Services' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Services

end
